### ISSUE TITLE
Warning 'PartitionAware connection strategy performs best if DiscoveryScope is set to cluster or datacenter' logged unnecessarily

### ISSUE THREAD

**Issue by gyorgy-giczi** [reuzel/CqlSharp#51]
Cluster.cs, OpenAsyncInternal():

		if (this._config.DiscoveryScope != DiscoveryScope.Cluster || this._config.DiscoveryScope != DiscoveryScope.DataCenter)
		{
			logger.LogWarning("PartitionAware connection strategy performs best if DiscoveryScope is set to cluster or datacenter", new object[0]);
		}

The condition is always true. You meant && instead of ||...

**Comment by reuzel** [comment]
Thanks will fix this ASAP.
